### PR TITLE
Make fail2ban with EL7 when firewalld is not used

### PR DESCRIPTION
**Pull request by martbhell**
Hi!

As a bonus also makes configuration.yml work if one does not have passwordless sudo on localhost.

### CODE REVIEW

**Comment by michaelrigart** [comment]
Hey @martbhell. It looks great. Currently at a conference, so I'll have a look at it in detail during the weekend.
Thx for the PR!

**Comment by michaelrigart** [comment]
Sorry for the late response. I totally forgot about this PR. I added some questions, because some things weren't totally clear to me.

**Comment by martbhell** [comment]
Oh. I forgot about this too. I have kept pushing things to our fork that were needed to make it work for us. Some changes might be about making it work on older version and or in Dockery 
.

**Comment by michaelrigart** [comment]
Hey @martbhell 

I made some changes to the role to accommodate all needs:
- I added the note for the fail2ban version (min 0.8 required)
- made some changes to use another banaction instead of firewalld

I'm not too keen on defining the default banaction in a custom jail.d config file. For me this has more to do with global configuration of fail2ban and less with jailing. So I find it a bit odd that the package maintainers of the fail2ban firewalld package throw it in there. 
What I have done is added a new task to remove custom jail.d config files ( this way you can remove the 00-firewalld.conf ). To set the default banaction to iptables-multiport you can choose to do nothing ( since this is already defined in the global jail.conf file, or add it to the custom jail.local file so it is again explicitly defined in your configuration.

I'm not going to merge the travis ci configuration and badge. I'm using Semaphore CI for this and I have configured it to setup 2 docker containers ( 1 ubuntu and 1 centos ) for testing purposes. 
You can keep the travis ci configuration in your fork.

**Comment by martbhell** [comment]
Thanks!  I'll check out the new.version :)

**Pull request closed without merging**
